create database uno;
use uno;
-- DROP DATABASE UNO;

-- Table: CLIENTE
CREATE TABLE CLIENTE (
    CODCLI CHAR(4) ,
    NOMCLI Varchar(50)  ,
APECLI Varchar(50),
    EMACLI Varchar(50)  ,
    CELCLI CHAR(9)  ,
    DIRCLI Varchar(50)  ,
    ESTCLI Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT CLIENTE_pk PRIMARY KEY (CODCLI)
);

-- Table: COMPRA
CREATE TABLE COMPRA (
    CODCOM Char(5)  ,
    FECCOM date  ,
    CODVEND CHAR(4)  ,
    CODPROV Char(5)  ,
    ESTCOM Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT COMPRA_pk PRIMARY KEY (CODCOM)
);

-- Table: COMPRADETALLE
CREATE TABLE COMPRADETALLE (
    IDCOMDET int  ,
    CODCOM Char(5)  ,
    CODPRO Char(5)  ,
    CANTPRO int NOT NULL,
    CONSTRAINT COMPRADETALLE_pk PRIMARY KEY (IDCOMDET)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO Char(5)  ,
    DESCPRO Varchar(50)  ,
    CATPRO Char(1)  ,
    PREPRO decimal(8,2)  ,
    STOCKPRO int  ,
    ESTPRO Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
);

-- Table: PROVEEDOR
CREATE TABLE PROVEEDOR (
    CODPROV Char(5)  ,
    RAZSOCPROV Varchar(50)  ,
    RUCPROV Varchar(11)  ,
    EMAPROV Varchar(50)  ,
    ESTPROV Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (CODPROV)
);

-- Table: VENDEDOR
CREATE TABLE VENDEDOR (
    CODVEND CHAR(4)  ,
    NOMVEND Varchar(50)  ,
    APEVEND Varchar(50)  ,
    EMAVEND Varchar(50)  ,
    CELVEND CHAR(9)  ,
    DIRVEND Varchar(50)  ,
    ESTVEND Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT VENDEDOR_pk PRIMARY KEY (CODVEND)
);

-- Table: VENTA
CREATE TABLE VENTA (
    CODVEN Char(5)  ,
    FECVEN DATE  ,
    CODCLI CHAR(4)  ,
    CODVEND CHAR(4)  ,
    ESTVEN Char(1) NOT NULL DEFAULT "A",
    CONSTRAINT VENTA_pk PRIMARY KEY (CODVEN)
);

-- Table: VENTADETALLE
CREATE TABLE VENTADETALLE (
    IDVENDET INT auto_increment ,
    CODVEN Char(5),
    CODPRO Char(5)  ,
    CANTPRO int NOT NULL,
    CONSTRAINT VENTADETALLE_pk PRIMARY KEY (IDVENDET)
);

/* Relacionar VENDEDOR_COMPRA */
ALTER TABLE COMPRA
ADD CONSTRAINT COMPRA_VENDEDOR FOREIGN KEY COMPRA_VENDEDOR (CODVEND)REFERENCES VENDEDOR (CODVEND);

/* Relacionar VENDEDOR_VENTA */
ALTER TABLE VENTA
ADD CONSTRAINT VENTA_VENDEDOR FOREIGN KEY VENTA_VENDEDOR (CODVEND)REFERENCES VENDEDOR (CODVEND);

/* Relacionar CLIENTE_VENTA */
ALTER TABLE VENTA
ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY VENTA_CLIENTE (CODCLI)REFERENCES CLIENTE (CODCLI);
   
/* Relacionar VENTADETALLE_VENTA */
ALTER TABLE VENTADETALLE
ADD CONSTRAINT VENTADETALLE_VENTA FOREIGN KEY VENTADETALLE_VENTA(CODVEN)REFERENCES VENTA (CODVEN);

/* Relacionar VENTADETALLE_PRODUCTO */
ALTER TABLE VENTADETALLE
ADD CONSTRAINT VENTADETALLE_PRODUCTO FOREIGN KEY VENTADETALLE_PRODUCTO (CODPRO) REFERENCES PRODUCTO (CODPRO);

/* Relacionar COMPRADETALLE_PRODUCTO */
ALTER TABLE COMPRADETALLE
ADD CONSTRAINT COMPRADETALLE_PRODUCTO FOREIGN KEY COMPRADETALLE_PRODUCTO (CODPRO) REFERENCES PRODUCTO (CODPRO);

/* Relacionar COMPRADETALLE_COMPRA */
ALTER TABLE COMPRADETALLE
ADD CONSTRAINT COMPRADETALLE_COMPRA FOREIGN KEY COMPRADETALLE_COMPRA (CODCOM)REFERENCES COMPRA (CODCOM);
   
 /* Relacionar COMPRA_PROVEEDOR */  
ALTER TABLE COMPRA
ADD CONSTRAINT COMPRA_PROVEEDOR FOREIGN KEY COMPRA_PROVEEDOR (CODPROV)REFERENCES PROVEEDOR (CODPROV);


INSERT INTO CLIENTE
(CODCLI, NOMCLI, APECLI, EMACLI, CELCLI, DIRCLI)
VALUES
("CLO1","Juana","Campos Ortiz","juana.campos@gmail.com","987485152","AV. Miraflores"),
("CLO2","Sofia","Barrios Salcedo","sofia.barrientos@gmail.com","","Jr. Huallaga"),
("CLO3","Claudio","Perez luna","claudio.perez@gmail.com","984512147","AV. Libertadores"),
("CLO4","Marcos","Avlia Marcos","marcos.avila@gmail.com","","Calle Huallaga"),
("CLO5","Anastacio","Salomon inti","anastacio.solano@gmail.com","","JR. San Martin");
select * FROM CLIENTE;

INSERT INTO VENDEDOR
(CODVEND, NOMVEND, APEVEND, EMAVEND, CELVEND, DIRVEND)
VALUES
("VEN1","Gloria","Carrizales Perez","gloria.carrizlaes@gmail.com","984574123","Calle las Beingoleas"),
("VEN2","Gabriel","Lozano Lombardi","gabriel.loazada@gmail.com","974512368","AV. LOS Girasoles"),
("VEN3","Gilberto","Martinez Guerra","gilverto.martinez@gmail.com","","JR. Los palomares");
select * FROM VENDEDOR;

INSERT INTO PROVEEDOR
(CODPROV, RAZSOCPROV, RUCPROV, EMAPROV)
VALUES
("PRV01","LG Corportation","87542136951","informes@lg.com.pe"),
("PRV02","SONY","45213698741","informes@sony.com.pe"),
("PRV03","SAMSUNG","85321697661","informes@samsung.com.pe"),
("PRV04","OSTER SRL","55663214478","informes@oster.com.pe"),
("PRV05","ASUS","99663325478","informes@asus.com.pe");
select * FROM PROVEEDOR;


INSERT INTO PRODUCTO
(CODPRO, DESCPRO, CATPRO, PREPRO,STOCKPRO)
VALUES
("PRO01","Refrigeradora LG side by side","1","4149","15"),
("PRO02","Refrigeradora SBS 602L","1","3599","10"),
("PRO03","Refrigeradora top mount 500l","1","2799","8"),
("PRO04","TV Samsumg UHD 55' ","2","1799","25"),
("PRO05","Televisor 65' LG UHD 4K","2","2999","20"),
("PRO06","TV CRYSTAL UDH 55' ","2","2299","7"),
("PRO07","ASUS X415KJA Core i3 10ºGen 14'","3","1099","17"),
("PRO08","Lenovo idealpat 5i Intel core i7 14'","3","3099","10"),
("PRO09","Laptop HP 15-DW1085la Intel Core i3","3","1600","15"),
("PRO10","Galaxi A52 128GB","4","1200","25"),
("PRO11","iPhone 11 64GB Morado","4","2600","30"),
("PRO12","Poco X3 GT 5G 256GB 8GB","4","1450","20");
select * FROM PRODUCTO;

select
CODCLI,
NOMCLI,
APECLI
CODPRO,
DESCPRO,
PREPRO
from CLIENTE
INNER JOIN PRODUCTO;

select
CODPROV,
RAZSOCPROV,
DESCPRO,
PREPRO,
STOCKPRO
from
PROVEEDOR
inner join PRODUCTO;


select
NOMVEND,
APEVEND,
EMAVEND,
CODVEN
from
VENDEDOR
inner join VENTA ;

